name: stock-sim
version: 0.1.0.0
author: Khanh
license: BSD3
github: "Khanh/stock-sim"
extra-source-files: []

# Thư viện dùng chung (src/)
library:
  source-dirs: src
  exposed-modules:
    - Controller
    - Helpers
    - Types
    - UI
  dependencies:
    - base >= 4.7 && < 5
    - brick
    - vty
    - stm
    - async
    - random
    - time
    - containers

# File chạy chính (app/Main.hs)
executables:
  stock-sim-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stock-sim
      - base >= 4.7 && < 5
      - brick
      - vty
      - stm
      - async
      - random
      - time
      - containers
